[package]
name = "alloy-ethers-typecast"
version = "0.1.0"
edition = "2021"
description = "Crate for safe typecasting between ethers and alloy types" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "40cc8cc54f7d36aa24147c937772600e5b119399" }
alloy-primitives = {version = "0.5.4" , features = ["rand"]} 

[lints.clippy]
all= "warn"