[package]
name = "alloy-ethers-typecast"
version = "0.1.0"
edition = "2021"
description = "Crate for safe typecasting between ethers and alloy types"
license = "CAL-1.0" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0.11"}
alloy-primitives = {version = "0.5.4" , features = ["rand"]} 

[lints.clippy]
all= "warn"

[package.metadata.docs.rs]
all-features = true