[package]
name = "alloy-ethers-typecast"
version = "0.2.0"
edition = "2021"
description = "Crate for safe typecasting between ethers and alloy types"
license = "CAL-1.0"
homepage = "https://github.com/rainlanguage/rain.interpreter" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0", features = ["legacy"] }
ethers-signers = { version = "2.0.8", features = ["ledger"] }
alloy-primitives = {version = "0.5.4" , features = ["rand"]}
alloy-sol-types = { version = "0.5.4" }
anyhow = "1.0.70"
tracing = "0.1.37"
serde_json = "1.0.111"

[dev-dependencies]
tokio = { version = "1.28.0", features = ["full"] }

[lints.clippy]
all= "warn"

[package.metadata.docs.rs]
all-features = true
