on: [push]

name: Crate

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Lint Check
        run: nix develop --command cargo clippy

      - name: Cargo Fmt
        run: nix develop --command cargo fmt --check

      - name: Cargo Test
        run: nix develop --command cargo test
